spring:
  application:
    name: payroll-api

server:
  port: ${PORT:8100}

eureka:
  client:
    register-with-eureka: true  
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}